### PR TITLE
some edits on using Refresh messages, and a few typos

### PR DESCRIPTION
**Pull request by moonshiner**
Take a look at these, I probably messed up one or two. Will go back and double check later this morning.

### CODE REVIEW

**Comment by Abhayakara** [comment]
These changes are actually inconsistent. We say "the latest update or refresh", which used to not be capitalized, and this means the latest action that was taken on the database, not the message that triggered that action. So either it should be "update message or refresh message" or it should be "update or refresh," not "update or refresh message."

I think the idea of capitalizing "Refresh" was to distinguish between the message and the transaction, but maybe I'm misremembering. Anyway, can you give this a think and see what occurs to you? I don't want to just ignore this pull request, but I don't think it's ready yet. :]

**Comment by moonshiner** [comment]
I was concerned I had gotten inconsistent, and you are correct.  

Initially I was making sure the document said "refresh message" when it was referring to one. 

I do like your idea of using "Refresh" for the message, but I would suggest writing "Refresh message" (or "refresh message" i'm open)  when it is the message.  Maybe that is overly obvious but it wasn't always to me. 

Can you look at this update?

**Comment by Abhayakara** [comment]
The problem with this pull request is that it feels like it's making things even more confusing. We're distinguishing between updates and refreshes, both of which are Update messages. The text feels like it's tugging us in the direction that Refresh messages are a distinct message type, but they're not. So I think this PR makes things worse, not better.

**Comment by Abhayakara** [comment]
(I'll take a stab at doing what you are trying to do, Tim—no worries!)

**Comment by moonshiner** [comment]
Thanks! and Thanks for figuring our where I was going with this; and triple thanks for doing the checks.

**Comment by Abhayakara** [comment]
Yeah, sorry it took me so long to figure out what the issue was. I think
you signaled it pretty clearly, but I was too focused on the typography. :]

**Pull request closed without merging**
